server:
  port: 9000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#   如果希望activi自行建表，数据库url加这个参数nullCatalogMeansCurrent=true
    url: jdbc:mysql://192.168.6.202:3306/bpm_demo?nullCatalogMeansCurrent=true
    username: root
    password: root
  #  autoconfigure:
  #    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  #  security:
  #    user:
  #      name: root
  #      password: root
  activiti:
    history-level: full
    db-history-used: true
    checkProcessDefinitions: false
